import pytest
from flask import g
from histarchexplorer.views.entity import (
    get_entity_images, get_parent_geometry, get_parent_geometry_id,
    adapt_map_dict, get_categorized_types, get_sub_count, get_hierarchy)
from histarchexplorer.api.presentation_view import (
    File, Relation, EntityTypeModel, PresentationView)

from unittest.mock import patch, MagicMock
from flask.testing import FlaskClient

def test_get_entity_images():
    from histarchexplorer import app
    files = [
        File(id=1, title='f1', render_type='image', main_image=True, license='L', public=True, url='U', mime_type='M', creator='C', license_holder='H', iiif_manifest='I', iiif_base_path='B', overlay=False, from_super_entity=False),
        File(id=2, title='f2', render_type='image', main_image=False, license='L', public=True, url='U', mime_type='M', creator='C', license_holder='H', iiif_manifest='I', iiif_base_path='B', overlay=False, from_super_entity=False),
        File(id=3, title='f3', render_type='unknown', main_image=False, license='L', public=True, url='U', mime_type='M', creator='C', license_holder='H', iiif_manifest='I', iiif_base_path='B', overlay=False, from_super_entity=False)
    ]
    with app.test_request_context():
        g.additional_files_for_overview = 1
        main, initial, all_imgs = get_entity_images(files)
        assert main.id == 1
        assert len(initial) == 1
        assert len(all_imgs) == 2

def test_get_parent_geometry():
    rel = Relation(id=1, name='R', system_class='S', geometries=[MagicMock()], geometry_json={'type': 'Point'})
    assert get_parent_geometry([rel]) == {'type': 'Point'}
    assert get_parent_geometry([]) == {}

def test_get_parent_geometry_id():
    rel = Relation(id=1, name='R', system_class='S', geometries=[MagicMock()], geometry_json={'type': 'Point'})
    assert get_parent_geometry_id([rel]) == 1
    assert get_parent_geometry_id([]) is None

def test_adapt_map_dict():
    geom = {'type': 'Feature', 'properties': {'title': 'T'}}
    res = adapt_map_dict(geom, 'Name', 1, 'Class')
    assert len(res) == 1
    assert res[0]['properties']['label'] == 'Name'
    
    geom_auto = {'type': 'Feature', 'properties': {'title': '(autogenerated) X'}}
    res = adapt_map_dict(geom_auto, 'Name', 1, 'Class')
    assert len(res) == 0

def test_get_categorized_types():
    types = [
        EntityTypeModel(id=1, title='T1', descriptions='D', is_standard=False, division={'label': 'Grave'}, type_hierarchy=[], value='V', unit='U'),
        EntityTypeModel(id=2, title='T2', descriptions='D', is_standard=True, division={'label': 'Other'}, type_hierarchy=[], value='V', unit='U')
    ]
    res = get_categorized_types(types)
    assert 'Grave' in res
    assert len(res['Grave']) == 1
    assert res['Grave'][0]['type'].id == 1

def test_get_sub_count():
    from histarchexplorer.api.presentation_view import PresentationView
    pv = PresentationView(id=1, system_class='place', view_class='v', title='T', description={}, aliases=[], start='S', end='E')
    rel = Relation(id=2, name='R', system_class='feature', relation_types=[{'relationTo': 1, 'property': 'crm:P46i_forms_part_of'}])
    pv.relations = {'feature': [rel]}
    res = get_sub_count(pv)
    assert res['count'] == 1
    assert res['ids'] == [2]

def test_get_entity_images_no_main():
    from histarchexplorer import app
    files = [
        File(id=1, title='f1', render_type='image', main_image=False, license='L', public=True, url='U', mime_type='M', creator='C', license_holder='H', iiif_manifest='I', iiif_base_path='B', overlay=False, from_super_entity=False)
    ]
    with app.test_request_context():
        g.additional_files_for_overview = 1
        main, initial, all_imgs = get_entity_images(files)
        assert main.id == 1
        assert len(initial) == 0 # because images.pop(0) was called before slicing?
        # Wait, get_entity_images:
        # main_image = images.pop(0)
        # initial_images = images[:g.additional_files_for_overview]
        # images.append(main_image)
        assert len(all_imgs) == 1

def test_get_hierarchy():
    from histarchexplorer.api.presentation_view import PresentationView
    pv = PresentationView(id=10, system_class='feature', view_class='v', title='T', description={}, aliases=[], start='S', end='E')
    place = Relation(id=1, name='P', system_class='place', geometries=[], geometry_json={})
    pv.relations = {'place': [place]}
    res = get_hierarchy(pv)
    assert len(res) == 1
    assert res[0].id == 1
    
    pv2 = PresentationView(id=20, system_class='stratigraphic_unit', view_class='v', title='T', description={}, aliases=[], start='S', end='E')
    feat = Relation(id=2, name='F', system_class='feature', relation_types=[{'relationTo': 20}])
    pv2.relations = {'feature': [feat], 'place': [place]}
    res = get_hierarchy(pv2)
    assert len(res) == 2

def test_entity_data_route(authenticated_client: FlaskClient):
    with patch('histarchexplorer.api.presentation_view.PresentationView.from_api') as mock_from:
        pv = PresentationView(id=1, system_class='place', view_class='v', title='T', description={}, aliases=[], start='S', end='E')
        pv.files = []
        pv.types = []
        pv.relations = {}
        mock_from.return_value = pv
        rv = authenticated_client.get('/entity-data/1')
        assert rv.status_code == 200

def test_get_rastermaps_invalid(authenticated_client: FlaskClient):
    rv = authenticated_client.post('/get_rastermaps', json={})
    assert rv.status_code == 400
    rv = authenticated_client.post('/get_rastermaps', json={'ids': 'not a list'})
    assert rv.status_code == 400
